My CV is available as a [pdf](cv.pdf), but also below

### Professional experience

||||
|:------------|-:|
| **Researcher**, Swedish University of Agricultural Sciences, Institute of Marine Research | 2022-- |
| **Post-doctoral researcher**, Swedish University of Agricultural Sciences, Institute of Marine Research | 2020--2022 |

### Education

||||
|:------------|-:|
| **Ph.D. Ecology**, Swedish University of Agricultural Sciences *Temperature- and body size scaling: effects on individuals, populations and food webs.* | 2016--2020 |
| **MRes.** Applied Marine and Fisheries Ecology (Distinction), University of Aberdeen. *Predicting spatial distribution of fish stocks by updating informative survey-based priors with commercial data in a Bayesian framework* | 2014--2015 |
| **BSc.** Biology, University of Gothenburg | 2011--2014 |

<!-- | Right | Left | Default | Center | -->

<!-- |------:|:-----|---------|:------:| -->

<!-- |   12  |  12  |    12   |    12  | -->

<!-- |  123  |  123 |   123   |   123  | -->

<!-- |    1  |    1 |     1   |     1  | -->


### Publications

[Google Scholar profile](https://scholar.google.se/citations?user=X-rwWCcAAAAJ&hl=en)

#### Preprints

_Papers are removed from here when published open access_

**Lindmark, M.**, Werner, M., Thor, P., Maioli, F., Quesada, E., Bartolino, V., Jacobson, P. 2025. Reduced size of larvae and small fish linked to warming and reduced prey density. *bioRxiv*, <https://doi.org/10.1101/2025.06.27.661664>


#### Publications

22\. **Lindmark, M.**, Maioli, M., Anderson, S.C., Gogina, M., Bartolino, V., Sk&ouml;ld, M., Ohlsson, M., Ekl&ouml;f, A., Casini, M. 2025. Quantifying competition between two demersal fish species from spatiotemporal stomach content data. *Canadian Journal of Fishery and Aquatic Sciences*, Accepted

21\. **Lindmark, M.**, Anderson, S.C., Thorson, J. 2025. Estimating scale-dependent covariate responses using two-dimensional diffusion derived from the SPDE method. *Methods in Ecology and Evolution*, Accepted

20\. **Lindmark, M.**, Griffiths, C.A., Bartolino, V., Thunell, V., Maioli, F., Anderson, S.C., Belgrano, A., Casini, M., Nadolna-A&lstrok;tyn, K., Pawlak, J., Pachur, M., Rakowski, M., Wikstr&ouml;m, K., Thompson, S.A.M., Gogina, M., Ustups, D., Jacobsen, N.S. 2025. Weak effects of local prey density and spatial overlap on predation intensity in a temperate marine ecosystem. *Ecological Applications*, Accepted

19\. Nor&eacute;n, K., Svensson, F., **Lindmark, M.** 2025. Evaluating the potential of underwater television to contribute to marine litter assessments alongside bottom trawling. *PLoS One* 20(6): e0324900. <https://doi.org/10.1371/journal.pone.0324900>

18\. Audzijonyte, A., Andersen, K.H., Atkinson, D., Bigman, J., Blanchard, J.L., Coghlan, A.R., Heather, F., **Lindmark, M.**, Morrongiello, J.R., Pauly, D. 2024. Temperature affects fish body sizes. Which sizes? *Global Change Biology*. 31(6), e70296. <https://doi.org/10.1111/gcb.70296>

17\. **Lindmark, M.**\*, Ohlberger, J.\*, G&aring;rdmark, A. 2025. Stronger effect of temperature on body growth in cool than in warm populations suggests lack of local adaptation. *Ecography*. e07518 (2025). <https://doi.org/10.1002/ecog.07518> * Dual first authorship.

16\. Ortega-Cisneros, K., Arcos, L.D.F,  **Lindmark, M.**\*, \[...\] Blanchard, J.L. 2025. An Integrated Global-to-Regional Scale Workflow for Simulating Climate Change Impacts on Marine Ecosystems. *Earth's Future*. 13(2) <https://doi.org/10.1029/2024EF004826>. _Author list truncated_ \*3/40

15\. Hansen, H. H., Bergman, E., Kopf, K., **Lindmark, M.** 2025. Resistance of Australian fish communities to drought and flood: implications for climate change and adaptations. *Ecography*. e07442 (2025). <https://doi.org/10.1111/ecog.07442>

14\. Blanchard, J. L. [...] __Lindmark, M.__* [...] Tittensor, D. 2024. Detecting, attributing, and projecting global marine ecosystem and fisheries change: FishMIP 2.0. *Earth's Future*. 12(12). <https://doi.org/10.1029/2023EF004402> _Author list truncated_ *31/43 

13\. Maioli, M., Weigel, B., **Lindmark, M.**, Manfredi, C., Zupa, W., Bitetto, I., Russo, T., Casini, M. 2024. Assessing the overlap between fishing activities and chondrichthyans distribution exposes high-risk areas for bycatch of threatened species. *Ecosphere*. 15(11). <https://doi.org/10.1002/ecs2.70050>

12\. Reum, J.C.P., Woodworth-Jefcoats, P., Novaglio, C., Forestier, R., Audzijonyte, A., G&aring;rdmark, A., **Lindmark, M.**, Blanchard, J.L. 2024. Temperature-dependence assumptions drive projected responses of diverse size-based food webs to warming. *Earth's Future*. 12(3). <https://doi.org/10.1029/2023EF003852>

11\. **Lindmark, M.**, Anderson, S.C., Gogina, M., Casini, M. 2023. Evaluating drivers of spatiotemporal variability in individual condition of a bottom-associated marine fish, Atlantic cod (*Gadus morhua*). *ICES Journal of Marine Science*, 80(5), 1539--1550 <https://doi.org/10.1093/icesjms/fsad084>

10\. **Lindmark, M.**, Karlsson, M., G&aring;rdmark, A. 2023. Larger but younger fish when growth outpaces mortality in heated ecosystem. *eLife*, 12, e82996. <https://doi.org/10.7554/eLife.82996>. *Featured on [The Naked Scientist podcast](https://www.thenakedscientists.com/articles/interviews/nuclear-fish-heat)

9\. Belgrano, A, **Lindmark, M.** 2023. Biodiversity transformations in the global ocean: a climate change and conservation management perspective. *Global Change Biology*, 29(12), 3235--3236 <https://doi.org/10.1111/gcb.16665>

8\. Woods, A.H, Moran, A.L. \[...\] **Lindmark, M.**\* \[...\], Verberk, C.E.P. 2022. Integrative approaches to understanding organismal responses to aquatic deoxygenation. *The Biological Bulletin*, 243(2), pp. 85--103. <https://doi.org/10.1086/722899> _Author list truncated_ \*16/26

7\. Audzijonyte, A., Jakubavi&#269;i&#363;t&#279;, E., **Lindmark, M.**, Richards, S.A. 2022. Mechanistic temperature-size rule explanation should reconcile physiological and mortality responses to temperature. *The Biological Bulletin*, 243(2), pp. 220--238. <https://doi.org/10.1086/722027>

6\. **Lindmark, M.**, Audzijonyte, A., Blanchard, J.L. G&aring;rdmark, A. 2022. Temperature impacts on fish physiology and resource abundance lead to faster growth but smaller fish sizes and yields under warming. *Global Change Biology*, 28(21), 6239--6253. <https://doi.org/10.1111/gcb.16341>

5\. **Lindmark, M.**, Ohlberger, J., G&aring;rdmark, A. 2022. Optimum growth temperature declines with body size within fish species. *Global Change Biology*, 28(7), pp. 2259--2271. <https://doi.org/10.1111/gcb.16067>

4\. Thunell, V., **Lindmark, M.**, Huss, M., G&aring;rdmark, A. 2021. Effects of warming on intraguild predator communities with ontogenetic diet-shifts. *The American Naturalist*. 196(6). 706--718. <https://doi.org/10.1086/716927>

3\. Huss, M., **Lindmark, M.**, Jacobson, P., van Dorst, R., G&aring;rdmark, A. 2019. Experimental evidence of gradual size-dependent shifts in body size and growth of fish in response to warming. *Global Change Biology*, 25(7), pp. 2285--2295. <https://doi.org/10.1111/gcb.14637>

2\. **Lindmark, M.**, Ohlberger, J., Huss, M. G&aring;rdmark, A. 2019. Size-based ecological interactions determine effects of warming on food web stability. *Ecology Letters*, 22(5), pp. 778--786. <https://doi.org/10.1111/ele.13235>

1\. **Lindmark, M.**, Huss, M., Ohlberger, J. G&aring;rdmark, A. 2018. Temperature-dependent body size effects determine population responses to climate warming. *Ecology Letters*, 21(2), pp. 181--189. <https://doi.org/10.1111/ele.12880>

### Reports

7\. RCG NANSEA RCG Baltic 2025. Regional Coordination Group North Atlantic, North Sea & Eastern Arctic and Regional Coordination Group Baltic. 2025. Part I Report, 72 pgs. Part II Decisions and Recommendations, 11 pgs. Part III, Intersessional Subgroup (ISSG) 2024-2025 Reports, 157 pgs.

6\. ICES. 2024. Joint ICES-PICES Working Group on Impacts of Warming on Growth Rates and Fisheries Yields (WGGRAFY; outputs from 2023 meeting). ICES  Scientific Reports. 6:70. 48 pp. <https://doi.org/10.17895/ices.pub.26356351>

5\. Jacobsen, N.S., Nadolna-Altyn, K., Ustups, D., **Lindmark, M.**, Griffiths, C., Abdullah, M., Balliu, D., Bartolino, V., Belgrano, A., Boois, I. de, Casini, M., Celie, L., Couce, E., Hal, R. van, Josias Nielsen, J., Kokubun, E.E., Kruze, E., Kvaavik, C., Lamb, P.D., Lemey, L., Levinsky, S.E., Maertens, I., Pachur, M., Pawlak, J., Pinnegar, J.K., Plantener, N., Quirijns, F.J., Raat, H., Rakowski, M., Scherffenberg Lundgaard, L., Sics, I., Stenersen Hansen, S.B., Stolk, D., Thompson, M.S.A., Torreblanca, E., Vingaard Larsen, P., Vinther, M., Wikstr&ouml;m, K., Wittoeck, J.. Study on stomach content of fish to update databases and analyse possible changes in diet or food web interactions, 2023, doi: [10.2926/683598](https://cinea.ec.europa.eu/publications/study-stomach-content-fish-update-databases-and-analyse-possible-changes-diet-or-food-web_en)

4\. ICES. 2023. Workshop 2 on Fish Distribution (WKFISHDISH2; outputs from 2022 meeting). ICES Scientific Reports. 5:7. 127 pp. <https://doi.org/10.17895/ices.pub.21692246>

3\. Havs- och vattenmyndigheten 2019. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2018.\
Resurs&ouml;versikt. Havs- och vattenmyndighetens rapport 2019:4. G&ouml;teborg, 305 s.

2\. Havs- och vattenmyndigheten 2018. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2017.\
Resurs&ouml;versikt. G&ouml;teborg, 273 s.

1\. Havs- och vattenmyndigheten 2016. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2016.\
Resurs&ouml;versikt


### Grants

||||
|:------------|-:|
| **Oscar and Lili Lamm Memorial Foundation** Principal Investigator of a one-year grant (grant no. FO2023-0037) 2024--2025. Project title: *Is the decline in size and body growth of Baltic Sea cod due to lack of food?* (995 546 SEK) | 2023 |
| **Formas research projects for early-career researchers** Principal Investigator of a four-year grant (2023--2026) from the Swedish Research Council Formas for Early Career Researchers (grant no. 2022-01511). Project title: *Improving estimates of climate-driven body size changes and range shifts in fishes by accounting for fine-scale spatial heterogeneity*. (3 990 209 SEK) | 2022 |
| **Sven och Dagmar Saléns stiftelse** (Travel grant) (5 616 SEK) | 2019 |
| **Knut and Alice Wallenbergs foundation** (Travel grant) (24 000 SEK) | 2018 |
| **SLU funds for internationalization of graduate education** (Travel grant) (28 000 SEK) (Travel grant) (24 000 SEK) | 2016 |


### Awards

||||
|:------------|-:|
| **SORTEE** Finalist of the SORTEE Open Science Researcher Award | 2023 |
| **Lindsay Laird Prize** In recognition of all-round performance in the Applied Marine and Fisheries Ecology program throughout the year. | 2015 |
| **Fishmonger's Award** Scholarship recipient: Full fees payment (£3400) awarded to 1 MRes/MSc student on academic merit by the Fishmonger's Company | 2014 |
| **Gothenburg Biological Society** Stipend for well accomplished bachelor's thesis: *By-catch in pelagic fisheries: A study on by-catch in Swedish herring fisheries on the west coast in the winter of 2013/2014* | 2014 |

 
### Invited talks

||||
|:------------|-:|
| **PICES-2023 Annual Meeting** (Seattle): *Non-linear growth-temperature relationship leads to opposite responses to warming in cold versus warm populations* | 2023 |
| **3rd Internal Water Seminar at SLU** (Uppsala): *Embracing local scale processes in climate-driven range shifts* | 2023 |
| **Svensk Fiskh&auml;lsa** (Uppsala): *Fish and fisheries in a changing climate* | 2022 |
| **Gulf of Maine Research Institute May Seminar (GMRI)** (video): *Understanding the effects of climate warming on food webs via individual-level physiology* | 2021 |

### Conferences

||||
|:------------|-:|
| **PICES Annual Meeting**, Seattle (Talk): *Non-linear growth-temperature relationship leads to opposite responses to warming in cold versus warm populations* | 2023 |
| **PICES 5th International Symposium on the Effects of Climate Change on the World's Ocean** ECCWO-5, Bergen (Talk): *Local changes in demersal fish biomass in relation to oxygen, temperature, and the metabolic index in a warming and deoxygenating ecosystem* | 2023 |
| **Swedish Oikos Meeting**, Gothenburg (Talk): *Quantifying competition between two demersal fish species* | 2023 |
| **ICES ASC** (Remote talk): *Higher mortality rates leave heated ecosystem with similar size structure despite larger, younger, and faster growing fish* | 2022 |
| **ICES/PICES Early Career Scientist Conference** (Talk): *Evaluating drivers of spatiotemporal changes in the condition of Eastern Baltic cod* | 2022 |
| **Swedish Oikos Meeting**, Online (Talk): *Evaluating drivers of spatiotemporal changes in the condition of Eastern Baltic cod* | 2021 |
| **Baltic Sea Science Congress**, Stockholm (Talk): *Warming alters the effect of fishing on the size spectra of an exploited temperate food web* | 2019 |
| **Society for Experimental Biology**, Seville (Talk). In Satellite: Is global warming causing animals to shrink? evidence, mechanisms and models: *Physiological constraints to growing large in warm waters?* | 2019 |
| **Swedish Oikos Meeting**, Uppsala (Talk): *Physiological constraints to growing large in warm waters?* | 2019 |
| **Models in Population Dynamics**, Ecology, and Evolution, Leicester (Talk): *Species interactions determine effects of warming on stability in a stage-structured food chain* | 2018 |
| **Nordic Oikos Meeting**, Trondheim (Talk): *Species interactions determine effects of warming on stability in a stage-structured food chain* | 2018 |
| **Swedish Oikos Meeting**, Lund (Talk): *Climate change and size-structured populations. Temperature dependent allometry and ontogenetic asymmetry shape warming responses of size structured populations* | 2017 |


### Working Groups

||||
|:------------|-:|
| **WGGRAFY**. Chair of joint ICES/PICES Working Group on Impacts of Warming on Growth Rates and Fisheries Yields | 2020-- |
| **WGECOBAL**. Member of Ecosystem-Based Fisheries Management of the Western Baltic Sea | 2025-- |
| **WGBIFS**. Member of the Baltic International Fish Survey Working Group | 2025-- |


### Teaching

||||
|:------------|-:|
| *Bl&aring; omst&auml;llning f&ouml;r h&aring;llbara hav och vatten ("Blue transformation for sustainable oceans")*. Lecture on global and national fisheries <https://github.com/maxlindmark/MOOC-course> | 2024 |
| *Principles in Fisheries Science*. Teaching assistant. Wrote R lab Impacts of fishing in an ecological context. Lecture on ecological interactions. <https://github.com/maxlindmark/pfs> | 2018-- |
| *Sustainability perspectives on contemporary fisheries. Where have all the fishes gone?* Teaching assistant. Lecture on climate impacts on global fisheries | 2019 |
| *Ecology for fish management and conservation*. Teaching assistant. Wrote R lab Population dynamics and harvesting, lecture on fish morphology, physiology, and energetics, supervising and grading student projects, exam questions and marking | 2016--2019 |

All lab material written by me is available on this github repository:\
<https://github.com/maxlindmark/comp-labs-ecology>


### Supervision

**Postdocs**

||||
|:------------|-:|
| Viktor Thunell, Swedish University of Agricultural Sciences | 2024-- |


**PhD students**

||||
|:------------|-:|
| Henry Hansen, Karlstad University (co-supervisor) | 2023--2024 |

**MSc students**

||||
|:------------|-:|
| Julia Cao Sanchez, Uppsala University. Main supervisor for project: *Joint species distribution modelling of benthic invertebrate communities* | 2023 |
| Leo Sheils, Uppsala University. Main supervisor for project: *Effects of warming on fish growth and body size* | 2023 |
| Malin Karlsson, Swedish University of Agricultural Sciences. Main supervisor for project: *The effect of temperature on life history traits of perch (Perca fluviatilis) in a large scale natural climate change experiment and its implications for population age- and size structure?* | 2019--2020 |
| Mattias Grunander, Swedish University of Agricultural Sciences. Co-supervisor for project: *Effects of global warming on Eurasian perch (Perca fluviatilis) in the Baltic Sea. - Does the growth response to increased temperatures differ along a latitudinal gradient?* | 2016 |

**BSc students**

||||
|:------------|-:|
| Lisa Sch&uuml;ttler, University of Gothenburg. Main supervisor for project: *Effects of heatwaves on fish size-at-age* | 2023 |


### Workshops

||||
|:------------|-:|
| Quantitative skill-sharing sessions | 2024 |
| Instructor at thesis writing workshop SLU | 2023 |
| Instructor at sdmTMB workshop in Bergen with IMR | 2023 |
| Lead grant writing workshop aimed towards ECRs at SLU Aqua | 2022 |
| *Making academic websites using GitHub, Quarto and RStudio*. <https://github.com/maxlindmark/quarto-website> | 2022 |
| *Making graphics in R for popular report on status of fishes in Swedish*. <https://github.com/maxlindmark/ROM> | 2022 |
| *LunchR*. A department wide R course in data wrangling and plotting (4x1 hour). Solely initiated and organized together with student colleague Philip Jacobson. Material: <https://github.com/maxlindmark/LunchR>. <https://github.com/maxlindmark/ROM> | 2018 |
| *Modelling population dynamics with MatCont*. Organized a session on numerical continuation analysis of a predator-prey model | 2018 |


### Reviewing

**Journals**: American Fisheries Society | American Naturalist | Canadian Journal of Fishery and Aquatic Sciences | Diversity & Distributions | Ecology | Ecology and Evolution | Ecology Letters | Environmental Biology of Fishes | Fisheries | Fish and Fisheries | Functional Ecology | Global Ecology and Biogeography | ICES Journal of Marine Science | Nature Communications | Nature Ecology and Evolution | Oikos | Peer J | PLOS ONE | Proceedings of the National Academy of Sciences | Proceedings of the Royal Society B | Reviews in Fish Biology and Fisheries | Science | Science Advances | Scientific Reports

**Proposals**: External evaluation of PhD proposal at Ifremer (2019)


### University Services

||||
|:------------|-:|
| PhD Representative. Department of Aquatic Resources, SLU | 2019 |
| Class representative. Applied Marine and Fisheries Ecology. I represented students' opinions and views on the program in regular meetings with course- and program coordinators at the University of Aberdeen | 2014--2015 |
| Student Ambassador. Applied Marine and Fisheries Ecology. I communicated with prospective students, mostly through social media | 2014--2015 |


### Outreach

||||
|:------------|-:|
| Interview about the paper [Larger but younger fish when growth outpaces mortality in heated ecosystem](https://doi.org/10.7554/eLife.82996) on [The Naked Scientist podcast](https://www.thenakedscientists.com/articles/interviews/nuclear-fish-heat) | 2023 |
| SLU 40th Anniversary, Uppsala (Poster). *Climate change and size-structured populations. Temperature dependent allometry and ontogenetic asymmetry shape warming responses of size structured populations* | 2017 |
| Science evenings (high school), &Ouml;sthammar municipality (Talk). *Effects of warming on fishes* | 2017 |
| Gothenburg Biological Society Popular talk at the Gothenburg Museum of Natural History on bycatch in small scale pelagic fisheries on the west coast of Sweden | 2014 |
| Swedish Society for Nature Conservation. I have given public talks (presenting on the topic of toxins in the Baltic herring in 2014) at local festivals (go: TO SEA and V&auml;sterhavsveckan) | 2011--2014 |
| Gothenburg Museum of Natural History. Arranged seminar (4\*2 per year) with invited speakers, covering all things marine | 2011--2014 |

