[Google Scholar profile](https://scholar.google.se/citations?user=X-rwWCcAAAAJ&hl=en)

# Publications
## Preprints

**Lindmark, M.**, Anderson, S. C., Gogina, M., and Casini, M. 2022. Evaluating drivers of spatiotemporal individual condition of a bottom-associated marine fish. *BioRxiv.* <https://www.biorxiv.org/content/10.1101/2022.04.19.488709v3>

## Publications

10\. **Lindmark, M.**, Karlsson, M., and G&aring;rdmark, A. 2023. Larger but younger fish when growth outpaces mortality in heated ecosystem. *eLife*, Accepted

9\. Belgrano, A, **Lindmark, M.** 2022. Biodiversity transformations in the global ocean: a climate change and conservation management perspective. *Global Change Biology*, early view. <https://doi.org/10.1111/gcb.16665>

8\. Woods, A. H, Moran, A. L. [...] **Lindmark, M.** [...], Verberk, C.E.P. 2022. Integrative Approaches to Understanding Organismal Responses to Aquatic Deoxygenation. *Biological Bulletin*, 243(2), pp. 85--103, <https://doi.org/10.1086/722899> *16/26

7\. Audzijonyte, A., Jakubavi&#269;i&#363;t&#279;, E., **Lindmark, M.**, Richards, S.A. 2022. Mechanistic temperature-size rule explanation should reconcile physiological and mortality responses to temperature. *Biological Bulletin*, 243(2), pp. 220--238. <https://doi.org/10.1086/722027>

6\. **Lindmark, M.**, Audzijonyte, A., Blanchard, J. L. and G&aring;rdmark, A. 2022. Temperature\
impacts on fish physiology and resource abundance lead to faster growth but smaller fish sizes\
and yields under warming. *Global Change Biology*, 28(21), 6239--6253,\ <https://doi.org/10.1111/gcb.16341>

5\. **Lindmark, M.**, Ohlberger, J., and G&aring;rdmark, A. 2022. Optimum growth temperature\
declines with body size within fish species. *Global Change Biology*, 28(7), pp. 2259--2271,\
<https://doi.org/10.1111/gcb.16067>

4\. Thunell, V., **Lindmark, M.**, Huss, M., and G&aring;rdmark, A. 2021. Effects of warming\
on intraguild predator communities with ontogenetic diet-shifts. *The American Naturalist*.\
196(6). 706--718, <https://doi.org/10.1086/716927>

3\. Huss, M., **Lindmark, M.**, Jacobson, P., van Dorst, R., G&aring;rdmark, A. 2019. Experimental\
evidence of gradual size-dependent shifts in body size and growth of fish in response\
to warming. *Global Change Biology*, 25(7), pp. 2285--2295, <https://doi.org/10.1111/gcb.14637>

2\. **Lindmark, M.**, Ohlberger, J., Huss, M. and G&aring;rdmark, A. 2019. Size-based ecological\
interactions determine effects of warming on food web stability. *Ecology Letters*,\
22(5), pp. 778--786, <https://doi.org/10.1111/ele.13235>

1\. **Lindmark, M.**, Huss, M., Ohlberger, J. and G&aring;rdmark, A. 2018. Temperature-dependent\
body size effects determine population responses to climate warming. *Ecology letters*,\
21(2), pp. 181--189, <https://doi.org/10.1111/ele.12880>

## Reports
ICES. 2023. Workshop 2 on Fish Distribution (WKFISHDISH2; outputs from 2022 meeting). ICES Scientific Reports. 5:7. 127 pp. https://doi.org/10.17895/ices.pub.21692246

Havs- och vattenmyndigheten 2019. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2018. Resurs&ouml;versikt. Havs- och vattenmyndighetens rapport 2019:4. G&ouml;teborg, 305 s.

Havs- och vattenmyndigheten 2018. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2017. Resurs&ouml;versikt. G&ouml;teborg, 273 s.

Havs- och vattenmyndigheten 2016. Fisk- och skaldjursbest&aring;nd i hav och s&ouml;tvatten 2016. Resurs&ouml;versikt